image: registry.gitlab.com/paddy-hack/nikola

test:
  script:
  - nikola build
  except:
  - master

pages:
  script:
    - pip install -U --upgrade-strategy=eager Nikola==8.0.0b2
    - nikola plugin --upgrade
    - nikola build
  artifacts:
    paths:
    - public
  only:
  - master

