image: registry.gitlab.com/paddy-hack/nikola
image: python:3

test:
  script:
  - apt-get install -y python-dev python-pip
  - nikola build
  except:
  - master

pages:
  script:
  - pip install -U --upgrade-strategy=eager Nikola==8.0.0b2
  - nikola plugin --upgrade
  - nikola build
  artifacts:
    paths:
    - public
  only:
  - master
