image: registry.gitlab.com/paddy-hack/nikola:8.0.0b2

test:
  script:
  - nikola build
  except:
  - master

pages:
  script:
    - nikola build
  artifacts:
    paths:
    - public
  only:
  - master
